const universities = [
    { name: 'Universität Wien' },
    { name: 'Wirtschafts Universität Wien' },
    { name: 'Technische Universität Wien' },
    { name: 'Universität Innsbruck' },
    { name: 'Universität Graz' },
    { name: 'Technische Universität Graz' },
    { name: 'Universität Salzburg' },
    { name: 'Universität Linz' },
    { name: 'Technische Universität München' },
    { name: 'Ludwig-Maximilians-Universität München' },
    { name: 'Technische Universität Berlin' },
    { name: 'Humboldt-Universität zu Berlin' },
    { name: 'Freie Universität Berlin' },
    { name: 'Charité - Universitätsmedizin Berlin' },
    { name: 'Universität Hamburg' },
    { name: 'HafenCity Universität Hamburg' },
    { name: 'Technische Universität Darmstadt' },
    { name: 'Goethe-Universität Frankfurt am Main' },
    { name: 'Johannes Gutenberg-Universität Mainz' },
    { name: 'Universität Stuttgart' },
    { name: 'Karlsruher Institut für Technologie' },
    { name: 'Eberhard Karls Universität Tübingen' },
    { name: 'Universität Heidelberg' },
    { name: 'Ruprecht-Karls-Universität Heidelberg' },
    { name: 'Universität Freiburg' },
    { name: 'Albert-Ludwigs-Universität Freiburg' },
    { name: 'Universität Konstanz' },
    { name: 'Universität Mannheim' },
    { name: 'Julius-Maximilians-Universität Würzburg' },
    { name: 'Universität Bayreuth' },
    { name: 'Universität Regensburg' },
    { name: 'Friedrich-Alexander-Universität Erlangen-Nürnberg' },
    { name: 'Technische Universität München' },
    { name: 'Universität Passau' },
    { name: 'Universität Leipzig' },
    { name: 'Technische Universität Dresden' },
    { name: 'Universität Rostock' },
    { name: 'Christian-Albrechts-Universität zu Kiel' },
    { name: 'Georg-August-Universität Göttingen' },
    { name: 'Universität Bremen' },
    { name: 'Universität Hannover' },
    { name: 'Technische Universität Braunschweig' },
    { name: 'Technische Universität Dortmund' },
    { name: 'Ruhr-Universität Bochum' },
    { name: 'Universität Duisburg-Essen' },
    { name: 'Universität zu Köln' },
    { name: 'Rheinische Friedrich-Wilhelms-Universität Bonn' },
    { name: 'Universität Siegen' },
    { name: 'Universität Paderborn' },
    { name: 'Universität Münster' },
    { name: 'Westfälische Wilhelms-Universität Münster' },
    { name: 'Technische Universität Clausthal' },
    { name: 'Universität Hildesheim' },
    { name: 'Universität Kassel' },
    { name: 'Justus-Liebig-Universität Gießen' },
    { name: 'Philipps-Universität Marburg' },
    { name: 'Technische Universität Ilmenau' },
    { name: 'Universität Jena' },
    { name: 'Friedrich-Schiller-Universität Jena' },
    { name: 'Bauhaus-Universität Weimar' },
    { name: 'Universität Greifswald' },
    { name: 'Universität Rostock' },
    { name: 'Universität Magdeburg' },
    { name: 'Otto-von-Guericke-Universität Magdeburg' },
    { name: 'Martin-Luther-Universität Halle-Wittenberg' },
    { name: 'Universität Erfurt' },
    { name: 'Technische Universität Bergakademie Freiberg' },
    { name: 'Friedrich-Schiller-Universität Jena' },
    { name: 'Universität Vechta' },
    { name: 'Universität Hamburg' },
    { name: 'Universität Oldenburg' },
    { name: 'Carl von Ossietzky Universität Oldenburg' },
    { name: 'Universität Osnabrück' },
    { name: 'Universität Potsdam' },
    { name: 'Sonstige'}
  ];
  export default universities